### ISSUE TITLE
Need help regarding regexes from Keyhacks repository

### ISSUE THREAD

**Issue by HackerAndya** [odomojuli/RegExAPI#11]
There are many other regexes than aforementioned. I need help creating all the regexes from the below repo.

https://github.com/streaak/keyhacks

Please let me know if I can get it.

**Comment by odomojuli** [comment]
I've amended the project description for clarity, in order to submit a regex pattern for entry, you must provide a source/explanation.

For context, key sniffers may contain deprecated or obsolete patterns with sparse guidance on what implementation they are searching for.

The intent of this project is to observe and verify specific patterns. Symmetry with pre-existing key sniffer projects is incidental but not a main priority.

If you would like to submit a specific pattern, you may open an issue with the name of the entry you are interested in.

For now, I appreciate the contribution but I will close this issue.
